import Nav from "@/components/Nav";
import "@/styles/globals.css";
import { icons } from "lucide-react";
import Head from "next/head";

export const metadata = {
  title: "Roushan Poddar",
  description: "Generated by Next.js",
  icons: {
    icon: ["/images/iconr4.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`scrollbar-hide`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
