import Nav from "@/components/Nav";
import "@/styles/globals.css";

export const metadata = {
  title: "Roushan Poddar",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`scrollbar-hide`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
